# == import files and libraries == #
from selenium.webdriver.common.by import By

# define the class...
class LoginPage:

    # define the constructor function that takes the driver parameter...
    def __init__(self, driver):
        self.driver = driver
        # identify the page element locators...
        self.username_textbox = (By.ID, "uname")
        self.password_textbox = (By.ID,"pwd")
        self.login_button = (By.XPATH, "//input[@value = 'Login']")

    # define the action function...
    def login_actions (self, url, username, password):
        # open the page...
        self.driver.get(url)
        # enter username...
        self.driver.find_element(*self.username_textbox).send_keys(username)
        # enter password...
        self.driver.find_element(*self.password_textbox).send_keys(password)
        # click button...
        self.driver.find_element(*self.login_button).click()
        # additional further actions...
        assert "Successful" in self.driver.page_source