# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPrjSuite01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testMainScreen01(self):
    self.driver.get("https://trytestingthis.netlify.app/")
    self.driver.set_window_size(1294, 1039)
    self.driver.find_element(By.ID, "fname").click()
    self.driver.find_element(By.ID, "fname").send_keys("John")
    self.driver.find_element(By.ID, "lname").send_keys("Doe")
    self.driver.find_element(By.ID, "male").click()
    self.driver.find_element(By.ID, "option").click()
    dropdown = self.driver.find_element(By.ID, "option")
    dropdown.find_element(By.XPATH, "//option[. = 'Option 1']").click()
    dropdown = self.driver.find_element(By.ID, "owc")
    dropdown.find_element(By.XPATH, "//option[. = 'Option 1']").click()
    dropdown = self.driver.find_element(By.ID, "owc")
    dropdown.find_element(By.XPATH, "//option[. = 'Option 3']").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(35)").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(38)").click()
    self.driver.find_element(By.ID, "moption").click()
    self.driver.find_element(By.NAME, "option2").click()
    self.driver.find_element(By.NAME, "Options").click()
    self.driver.find_element(By.NAME, "Options").send_keys("Vanilla")
    self.driver.find_element(By.ID, "favcolor").click()
    self.driver.find_element(By.ID, "favcolor").send_keys("#d1b500")
    self.driver.find_element(By.ID, "day").click()
    self.driver.find_element(By.ID, "day").click()
    self.driver.find_element(By.ID, "day").send_keys("2024-11-13")
    self.driver.find_element(By.ID, "a").send_keys("82")
    self.driver.find_element(By.ID, "a").click()
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.ID, "quantity").send_keys("1")
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.ID, "fname").send_keys("2")
    self.driver.find_element(By.ID, "quantity").click()
    self.driver.find_element(By.NAME, "message").click()
    self.driver.find_element(By.NAME, "message").send_keys("The cat was playing in the garden. Great!")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "uname").click()
    self.driver.find_element(By.ID, "uname").send_keys("test")
    self.driver.find_element(By.ID, "pwd").click()
    self.driver.find_element(By.ID, "pwd").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h2")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "fname").click()
  
